###  Getting stated with Jupyter Notebook

### Libraries or Modules

In [1]:
import math

In [2]:
math.sqrt(25)

5.0

In [3]:
math.pi

3.141592653589793

In [4]:
import math as mt

In [5]:
mt.sqrt(25)

5.0

In [9]:
from numpy import random
import numpy as np

In [10]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)

In [11]:
dataOne

array([[0.56692827, 0.16122361, 0.88883847, 0.34644083, 0.79694223],
       [0.80438598, 0.41550222, 0.27153853, 0.28055034, 0.35694444],
       [0.65437167, 0.67414226, 0.97008071, 0.78102254, 0.26504952],
       [0.86365533, 0.44289022, 0.43653445, 0.94399166, 0.97233424],
       [0.60426392, 0.19181039, 0.86504292, 0.73310224, 0.01948573]])

In [12]:
np.mean(dataOne)

0.5722829095174747

In [16]:
#rounding off values
round_off_values = np.round_(dataOne,decimals = 3)

In [17]:
round_off_values

array([[0.567, 0.161, 0.889, 0.346, 0.797],
       [0.804, 0.416, 0.272, 0.281, 0.357],
       [0.654, 0.674, 0.97 , 0.781, 0.265],
       [0.864, 0.443, 0.437, 0.944, 0.972],
       [0.604, 0.192, 0.865, 0.733, 0.019]])

In [24]:
#power values 
power_values = np.power(dataOne,2)

In [26]:
power_values

array([[3.21407664e-01, 2.59930513e-02, 7.90033818e-01, 1.20021249e-01,
        6.35116921e-01],
       [6.47036806e-01, 1.72642096e-01, 7.37331745e-02, 7.87084931e-02,
        1.27409336e-01],
       [4.28202280e-01, 4.54467787e-01, 9.41056593e-01, 6.09996213e-01,
        7.02512495e-02],
       [7.45900521e-01, 1.96151746e-01, 1.90562326e-01, 8.91120250e-01,
        9.45433877e-01],
       [3.65134891e-01, 3.67912267e-02, 7.48299258e-01, 5.37438902e-01,
        3.79693655e-04]])

In [27]:
#statistics - percentile
np.percentile(dataOne, 50)

0.6042639249623553

In [30]:
np.median(dataOne)

0.6042639249623553

In [36]:
np.std(dataOne)

0.2803994441598422

In [48]:
from scipy import stats
import scipy as sp
sp.mean(dataOne)
desc = stats.describe(dataOne) 
desc

DescribeResult(nobs=5, minmax=(array([0.56692827, 0.16122361, 0.27153853, 0.28055034, 0.01948573]), array([0.86365533, 0.67414226, 0.97008071, 0.94399166, 0.97233424])), mean=array([0.69872103, 0.37711374, 0.68640702, 0.61702152, 0.48215123]), variance=array([0.01665669, 0.04374301, 0.09697805, 0.08342683, 0.1540605 ]), skewness=array([ 0.3182093 ,  0.3092306 , -0.46445615, -0.19686251,  0.17445094]), kurtosis=array([-1.59223706, -1.17801109, -1.58132611, -1.63003374, -1.4747716 ]))

### Functions

In [49]:
print('I Love data Science')

I Love data Science


In [50]:
from scipy import mean 
print("\nArithmetic Mean is with default axis = 0 : \n",  
      mean(dataOne, axis = 0)) 
  


Arithmetic Mean is with default axis = 0 : 
 [0.69872103 0.37711374 0.68640702 0.61702152 0.48215123]


### Variables

In [59]:
variableName = 25
type(variableName)

int

In [60]:
variableName1 = 'I Love data Science'
print(variableName1)

I Love data Science


### Datatypes

In [55]:
variableName = 25.0
type(variableName)

float

### List and Directories

In [75]:
listOne = [1,2,3,4]
print(listOne[1:3])


[2, 3]


In [77]:
tel = {'jack': 4098, 'sape': 4139}

In [78]:
tel['jack']

4098